### ISSUE TITLE
force close on honeycomb with talkback (low-vision accessibility) enabled

### ISSUE THREAD

**Issue by dpadgett** [dpadgett/Timer#1]
this was a report sent in from google play.  of the devices I tried (gingerbread, honeycomb, and ICS) it only happens on honeycomb.  talkback must be enabled, under accessibility, to cause the force close.  here's the stack trace from the google play report:

android.view.InflateException: Binary XML file line #23: Error inflating class org.dpadgett.widget.FasterNumberPicker
at android.view.LayoutInflater.createView(LayoutInflater.java:596)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:671)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:724)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:727)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:727)
at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
at android.view.LayoutInflater.inflate(LayoutInflater.java:391)
at org.dpadgett.timer.CountdownFragment.onCreateView(CountdownFragment.java:77)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:870)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1080)
at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:622)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1416)
at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:431)
at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:139)
at android.support.v4.view.ViewPager.populate(ViewPager.java:804)
at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1016)
at android.view.View.measure(View.java:10853)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4353)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:267)
at android.view.View.measure(View.java:10853)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:764)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:519)
at android.view.View.measure(View.java:10853)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4353)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:267)
at android.view.View.measure(View.java:10853)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4353)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1284)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:613)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:519)
at android.view.View.measure(View.java:10853)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4353)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:267)
at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2042)
at android.view.View.measure(View.java:10853)
at android.view.ViewRoot.performTraversals(ViewRoot.java:941)
at android.view.ViewRoot.handleMessage(ViewRoot.java:2066)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:132)
at android.app.ActivityThread.main(ActivityThread.java:4126)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:491)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:844)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.constructNative(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:416)
at android.view.LayoutInflater.createView(LayoutInflater.java:576)
... 44 more
Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
at android.content.res.Resources.getText(Resources.java:238)
at android.content.res.Resources.getString(Resources.java:322)
at android.content.res.Resources.getString(Resources.java:350)
at android.content.Context.getString(Context.java:217)
at org.dpadgett.widget.FasterNumberPicker.updateInputTextView(FasterNumberPicker.java:2065)
at org.dpadgett.widget.FasterNumberPicker.<init>(FasterNumberPicker.java:758)
at org.dpadgett.widget.FasterNumberPicker.<init>(FasterNumberPicker.java:569)
... 47 more

**Comment by dpadgett** [comment]
fixed this ages ago
